
runtime: python27
threadsafe: yes
api_version: 1



handlers:
- url: /(.*)
  static_files: dist/client/index.html
  upload: dist/client/index.html

- url: /(.*)
  static_files: dist/client/\1
  upload: dist/client/(.*)

 
skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE





  
 


  

