orbs: # declare what orbs we are going to use
  node: circleci/node@2.0.2 # the node orb provides common node-related configuration

version: 2.1 # using 2.1 provides access to orbs and other features
executors:
   node:
     docker:
       - image: cimg/16.13.0

jobs:
  install-dependencies:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-packaging-dependencies-{{ checksum "package-lock.json"}}
            - v4-packaging-dependencies-
      - run:
          name: install-dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v4-packaging-dependencies-{{ checksum "package-lock.json" }}
  
  run_app:
    executor: node
    steps:
      - checkout
      - restore_cache:
         keys:
           - v4-packaging-dependencies-{{ checksum "package-lock.json"}}
           - v4-packaging-dependencies-
      - run: 
          name: run_app
          command: npm run dev

  unit-test:
    executor: node
    steps:
      - checkout
      - restore_cache:
         keys:
           - v4-packaging-dependencies-{{ checksum "package-lock.json"}}
           - v4-packaging-dependencies-
      - run:
          name: unit-test
          working_directory: client
          command: ng test


workflows:
  matrix-tests:
    jobs:
      - install_dependencies
      - run_app:
          requires:
            - install-dependencies
      - unit_test:
          requires:
            - install-dependencies
     
