orbs:
  common: okode/common@2.0.13
  node: circleci/node@4 # the node orb provides common node-related configuration

description: |
  Build and publish Angular libraries.
  Repository: https://github.com/okode/orbs

version: 2.1 # using 2.1 provides access to orbs and other features
executors:
   node:
     docker:
       - image: cimg/node:16.13.0
     

jobs:
  install-dependencies:
    executor:
      name: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-packaging-dependencies-{{ checksum "package-lock.json"}}
            - v4-packaging-dependencies-
      - run:
          name: install_dependencies
          command: npm install
      - run:
          name: install-concurrency
          command: sudo npm install -g concurrently
      
      - save_cache:
          paths:
            - node_modules
          key: v4-packaging-dependencies-{{ checksum "package-lock.json" }}
  
  install-concurrency:
      executor: node
      steps:
        - checkout
        - run:
            name: install-concurrency
            command: sudo npm install -g concurrently
  
  run_server:
    executor:
      name: node
    steps:
      - checkout

      - run:
          name: install_dependencies
          working_directory: server
          command: |
            npm install
            npm run build

  unit-test:
    executor: node
    steps:
      - checkout
      - run:
          name: install_dependencies
          working_directory: client
          command: npm install

      - run:
          working_directory: client
          command: npm run build

  
      
      - run:
          name: unit-test
          working_directory: client
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI


workflows:
  matrix-tests:
    jobs:
      - unit-test
           
      
      
      
     
