orbs:
  common: okode/common@2.0.13
  node: circleci/node@4 # the node orb provides common node-related configuration
  cypress: cypress-io/cypress@1


version: 2.1 # using 2.1 provides access to orbs and other features
executors:
   node:
     docker:
       - image: cimg/node:16.13.0
   with-chrome:
    resource_class: small
    docker:
      - image: "cypress/browsers:node14.16.0-chrome90-ff88"
     

jobs:
  install-client-dependencies:
    executor:
      name: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v8-packaging-dependencies-{{ checksum "client/package-lock.json"}}
            
      - run:
          name: install_client_dependencies
          working_directory: client
          command: |
           npm ci
           sudo npm install -g concurrently

      - run:
          name: install_cypress_dependencies
          command: |
             npm install
             sudo npm install -g concurrency
             npm install --save-dev cypress

      - save_cache:
          paths:
            - client/node_modules
            - /usr/local/lib
           
          key: v8-packaging-dependencies-{{ checksum "client/package-lock.json" }}
   
            
  
  
  run_server:
    executor:
      name: node
    steps:
      - checkout

      - run:
          name: install_dependencies
          working_directory: server
          command: |
            npm install
            npm run build

  unit-test:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v8-packaging-dependencies-{{ checksum "client/package-lock.json" }}
      
      - run:
          name: unit-test
          working_directory: client
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  
      

  build:
    executor: node
    steps:
      - checkout
      - restore_cache:
           keys:
             - v8-packaging-dependencies-{{ checksum "client/package-lock.json"}}
      - run:
          name: build_front_end
          working_directory: client
          command: npm run build
      
      - persist_to_workspace:
          root: client/dist
          paths:
            - ./*

  cypress:
    executor: node
    steps:
      - checkout
      - run:
          name: install_cypress_dependencies
          command: |
             npm install
             sudo npm install -g concurrently
             npm install --save-dev cypress
     

      - run:
          name: e2e-tests
          command: npm run dev
      

  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - attach_workspace:
          at: client/dist
      - restore_cache:
           keys:
             - v8-packaging-dependencies-{{ checksum "client/package-lock.json"}}
            
      - run:
          name: Set up gcloud config
          command: |
            echo ${GCLOUD_KEY} > /tmp/sa_key.json 
            gcloud auth activate-service-account --key-file=/tmp/sa_key.json
            rm /tmp/sa_key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}  

      - run:
          name: deploy
          working_directory: client
          command: gcloud app deploy app.yaml --version="version-client"
          


      
      

workflows:
  matrix-tests:
    jobs:
      - install-client-dependencies
      - cypress/run:
         working_directory: client
         executor: with-chrome
         browser: chrome
         requires:
            - install-client-dependencies
         cache-key: 'v6-packaging-dependencies-{{ checksum "client/package-lock.json"}}'
         start: npm run dev
      - unit-test:
           requires:
              - install-client-dependencies
      
      - build:
          requires:
            - unit-test

      - deploy:
          requires:
            - build
        
           
      
      
      
     
