# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [closed]
    branches: [ master ]

jobs:
  delete_merged_versions:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3  
      - uses: nelonoel/branch-name@v1.0.1
      - uses: google-github-actions/auth@v0.4.0
        with:
           credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: PR_versions
        if: github.event.pull_request.merged == true
        run: |
           echo ${{ github.event.pull_request.head.ref }}
           VERSION=`echo ${{ github.event.pull_request.head.ref }} | tr -dc '[:alnum:]\n\r' |  tr  '[:upper:]' '[:lower:]'`
           VERSION_CLIENT="client-${VERSION}"
           VERSION_SERVER="server-${VERSION}"
           gcloud app versions delete --service=server-service $VERSION_SERVER
           gcloud app versions delete --service=default $VERSION_CLIENT
           
  delete_merged_branches:
       needs:  delete_merged_versions
       runs-on: ubuntu-latest
       steps:
       - uses: actions/checkout@v3
       - uses: SvanBoxel/delete-merged-branch@main
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
