# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [closed]
    branches: [ master ]

jobs:
  delete_merged_branches:
     runs-on: ubuntu-latest
     if: |
      (github.event_name == 'push' && !contains(github.event.head_commit.message, 'Merge pull request')) ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
     steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3    
      - run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
