# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [closed]
    branches: [ master ]

jobs:
  delete_merged_branches:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3   
      - uses: nelonoel/branch-name@v1.0.1
      - name: PR_name
        if: (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
        run: echo "${BRANCH_NAME}"
      
